# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: job1
    steps:
    - script: echo terraform task

    - task: DownloadSecureFile@1
      name: publickey
      inputs:
        secureFile: 'id_rsa.pub'

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
        commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret)  -var ssh_public_key=$(publickey.secureFile)'
        backendServiceArm: 'test-azure-service-connection'
        backendAzureRmResourceGroupName: 'user131_rg'
        backendAzureRmStorageAccountName: 'storagefordevops'
        backendAzureRmContainerName: 'containerfordevops'
        backendAzureRmKey: 'tf/terraform.tfstate'
